### ISSUE TITLE
Option to change keyboard shortcut

### ISSUE THREAD

**Issue by Ser-Gen** [nwjlyons/google-search#4]
I can't use same shortcut of package [sergeche/emmet-sublime](https://github.com/sergeche/emmet-sublime): `Shift+Ctrl+G` (Wrap With Abbreviation).

**Comment by ionutvmi** [comment]
You can change the shortcut by going to Preferences -> Key Bindings User and add this configuration

```
    {
        "keys": ["ctrl+shift+g"], "command": "google_search"
    },
    {
        "keys": ["ctrl+alt+g"], "command": "google_search_any"
    }
```

**Comment by Ser-Gen** [comment]
Yep, I have tried this ability.
```json
[
	{ "keys": ["ctrl+shift+u"], "command": "google_search" },
	{ "keys": ["ctrl+alt+u"], "command": "google_search_any" }
]

```
With this setting Google Search start using both shortcuts, `ctrl+shift+g` and `ctrl+shift+u` :\

**Comment by ionutvmi** [comment]
I think that happens because the search plugin is loaded after the emmet one.

You can have a look at the configuration from the emmet plugin and copy/paste from there what you want to take priority to your Key Bindings User file.
https://github.com/sergeche/emmet-sublime/blob/master/Default%20(Windows).sublime-keymap#L267

**Comment by Ser-Gen** [comment]
It helps! Thank you!

**Comment by ionutvmi** [comment]
Awesome, closing this issue as the issue is resolved.
